esphome:
  name: "esphome-web-gosnik"
  friendly_name: esp32-mic-speaker
  #name_add_mac_suffix: true
  

esp32:
  board:  esp32dev #esp-wrover-kit
  framework:
    type: arduino



# Enable logging
logger:
 level: DEBUG
# Enable Home Assistant API
api:

ota:
 - platform: esphome
   id: ota_esphome

wifi:
  ssid: ""
  password: ""
  #ssid: !secret wifi_ssid
  #password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Rozruch w trybie awaryjnym

  - platform: factory_reset
    id: factory_reset_btn
    name: Przywracanie ustawień fabrycznych


i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO23
    i2s_bclk_pin: GPIO19
  
  - id: i2s_in
    i2s_lrclk_pin: GPIO33
    i2s_bclk_pin: GPIO32 
    

microphone:
  - platform: i2s_audio
    i2s_audio_id: i2s_in
    adc_type: external
    id: echo_microphone
    i2s_din_pin: GPIO35
    pdm: False
    channel: right
    bits_per_sample: 16bit




    
media_player:
  - platform:  i2s_audio
    i2s_audio_id: i2s_audio_bus
    name: "ESPHome I2S Media Playr"
    id: player
    dac_type: external
    i2s_dout_pin: GPIO22   #DIN 
    mode: mono
    i2s_comm_fmt: msb
    on_play:
      - logger.log: "playing"
      - switch.turn_off: use_wake_word
      - voice_assistant.stop: # Wymusza natychmiastowe zatrzymanie asystenta
    on_pause:
      - logger.log: "paused"
      - switch.turn_off: use_wake_word
    on_idle:
      - logger.log: "idle"
      - delay: 1s # Chwila oddechu dla procesora
      - switch.turn_on: use_wake_word      


voice_assistant:
  id: va
  microphone: echo_microphone
  media_player: player
  use_wake_word: true
  on_stt_end:
    - logger.log: "Listening stopped."
    - media_player.turn_on: player # Włącza głośnik, gdy nasłuchiwanie się kończy
  
  on_listening:
    - logger.log: "Listening..."
    - media_player.turn_off: player # Wyłącza głośnik na czas nasłuchu

  

 
  
  

  

binary_sensor:
  - platform: status
    name: API Connection
    id: api_connection
    filters:
      - delayed_on: 1s
    


switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: ALWAYS_OFF
    entity_category: config
    on_turn_on:
      
      - voice_assistant.start:

    on_turn_off:
      - voice_assistant.stop
